---
kind: pipeline
type: docker
name: bind zone test
platform:
  os: linux
  arch: amd64
clone:
  depth: 50
  tags: true
  skip_verify: true
steps:
- name: test
  image: nixos/nix
  commands: 
  - curl http://ifconfig.co
    #  - nix-channel --update
    #- nix-shell -I 'nixpkgs=channel:nixos-unstable' -p bash bind --run 'bash checkzones'
    #- cd dn42
    #- nix-shell -I 'nixpkgs=channel:nixos-unstable' -p bash bind --run 'bash checkzones' 
- name: deploy
  image: nixos/nix
  volumes:
  - name: zones
    path: /dns
  commands:
  - rm -rf /dns/db.* && rm -rf /dns/dn42/db.*
  - cp db.* /dns/
  - cp dn42/db.* /dns/dn42
- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://litschi.xyz
    roomid: oluuLjSMgyzTBlZiZl:litschi.xyz
    username:
      from_secret: user
    password:
      from_secret: password
volumes: 
  - name: zones
    host:
      path: /var/dns/
